### ISSUE TITLE
Ability to pass flags (parameters)

### ISSUE THREAD

**Issue by vitalybe** [NicoSantangelo/sublime-gulp#18]
In our gulp the tasks can receive flags, e.g, I can run `gulp build` or `gulp build --watch`.

How do I pass flags with sublime-gulp?

**Comment by NicoSantangelo** [comment]
Hello! I never used arguments in my tasks so I didn't add this feature (so it's not possible right now), but I think is a good idea.

I'll give it a try, but can you give me an example of some task that uses flags please? so I can test locally.

Thanks!

**Comment by vitalybe** [comment]
I ended up just using shell to run gulp, however, I still think it could be added as a nice feature. For example, we pass an `environment` flag to our gulp, like so: `gulp build --env=windows`

Then we check it inside like so:

    var argv = require('minimist')(process.argv.slice(2));
    var env = argv.env || null;

**Comment by cperryk** [comment]
+1. We use the --cwd flag with gulp because have a single gulp file servicing many little projects.

**Comment by NicoSantangelo** [comment]
Sorry for the big delay. I have a local branch for this feature but I haven't been able to get significant progress.

It might be taking me a lot more than expected but I'll keep you posted when I have something.

**Comment by NicoSantangelo** [comment]
I finally got around doing this feature, sorry for the massive delay.

I'll close this for now but if you have any feedback let me know and I'll reopen it.
