### ISSUE TITLE
Not sure if it's an issue

### ISSUE THREAD

**Issue by alanontheweb** [NicoSantangelo/sublime-gulp#19]
Hi, I had this plugin working just fine and then I made some big configuration changes to my gulpfile.js. Using the terminal I can still run gulp tasks no problem, but now when I run the Gulp command from Sublime, it doesn't display the dropdown menu with my tasks. I have commented out most of the file to just 1 basic task and it's still not working.

Under the sublime-gulp.cache, this is what I see - {"/Users/USER/Documents/Projects/Classrooms/gulpfile.js":{"sha1":"675f25c0b61304bbe9012c70bcf78ca34459707","tasks":{}}}

It doesn't generate an error log either.

Thoughts?

**Comment by NicoSantangelo** [comment]
Huuum, are you defining `gulp` as a local variable inside of your `gulpfile`? Like this:

````
var gulp = require('gulp');
````

If that's not it and it's not a problem, post your `gulpfile` so I can try it locally :)

**Comment by alanontheweb** [comment]
Thanks. Yeah, I have that defined. Like I said, it used to work fine and it still works fine in the terminal. In Sublime I see the working indicator at the bottom for a split second. It doesn't error out or anything. Nothing else happens.

Here's my gulp file (it's very messy and long, since it's a WIP), but most things are commented out.

// Setup

// var inject = require('gulp-inject');
// var cdnizer = require('gulp-cdnizer');
// gulp.task('mytask', function(){
//   var target = gulp.src('./src/index.html');
//   return gulp.src('*')
//   .pipe(prompt.prompt({
//         type: 'input',
//         name: 'type',
//         message: 'What you like to do? [cdn/assets]'
//     }, function(res){
//         var sources;
//         if(res.type === 'cdn'){
//           sources = ...
//           target.pipe(inject(sources))
//           .pipe(gulp.dest('./src'));
//         }else{
//           target.pipe(cdnizer({...});
//         }

//     }));
// });


// return gulp.src('app/**/*.html')
//     .pipe(assets)
//     // Concatenate And Minify JavaScript
//     .pipe($.if('*.js', $.uglify({preserveComments: 'some'})))
//     // Remove Any Unused CSS
//     // Note: If not using the Style Guide, you can delete it from
//     // the next line to only include styles your project uses.
//     .pipe($.if('*.css', $.uncss({
//       html: [
//         'app/index.html',
//         'app/styleguide.html'
//       ],
//       // CSS Selectors for UnCSS to ignore
//       ignore: [
//         /.navdrawer-container.open/,
//         /.app-bar.open/
//       ]
//     })))
//     // Concatenate And Minify Styles
//     // In case you are still using useref build blocks
//     .pipe($.if('*.css', $.csso()))
//     .pipe(assets.restore())
//     .pipe($.useref())
//     // Update Production Style Guide Paths
//     .pipe($.replace('components/components.css', 'components/main.min.css'))
//     // Minify Any HTML
//     .pipe($.if('*.html', $.minifyHtml()))
//     // Output Files
//     .pipe(gulp.dest('dist'))
//     .pipe($.size({title: 'html'}));
// });


// For this to work on Foundation 5, had to add this to 
// options: ignore : [/meta\..+/] 
// Otherwise Syntax error, unrecognized expression: [data-'Times New Roman'-abide] is thrown.


var gulp = require('gulp');
var critical = require('critical').stream;
var gulpLoadPlugins = require('gulp-load-plugins');
var $ = gulpLoadPlugins({
    rename: {
        'gulp-minify-css': 'minifycss',
        'gulp-browser-sync': 'browserSync',
        'gulp-scss-lint': 'scssLint'
    }
});


//gulp sketch
//Sketch tools

// return gulp.src('path/to/source/**/*.scss')
//   .pipe(sassdoc())
//   .pipe(sass())
//   .pipe(gulp.dest('path/to/styles'));

//sassdoc
//jsdoc

//sc5 STYLEGUIDE GENERATOR!!!

//Flatten to Production Environment

//run pagespeed insights


/*
    1. COMPILE TO TEST ENVIRONMENT
    
    ~ Combine and compile KIT/Markdown partials and copy extra HTML files into /test-build/**
    
    ~ combine and compile SASS partials,run auto-prefixer, run SCSSLint, run Bless, and generate sourcemaps for
    /test-build/assets/app.css/ 
    Run SassDoc

    
    ~ combine and compile JS partials , run JSHint, into /test-build/assets/app.js
    ~ Run DOXX

    ~ run BrowserSync
    ~ Run Takana

    ~ Compress images  Handles PNG, JPEG, GIF and SVG images
        cleansketch
        imagemin
        generate webp
        generate responsive images
        generate * svg symbols sprite
        inline svg optional
        
        svg-sprite - symbols w/ external 'use' -use svg for everybody polyfill
        gulp favicons
    

 ~ run BrowserSync
    ~ Run Takana

 ~copy fonts from bower directory into /test-build/assets/fonts/
gulp-fontgen
fontface Generator of browser fonts and css from ttf or otf files



inline source
    inline javascript
    inline svg through AJAX for better browser support (multiple requests... but cached)


expiry date with gulp-rev-all
    
    */

// Environment variables and config

var env = {
    Source: 'src/', // Source path
    Test: 'test-build/', // Test build path
    Prod: 'prod-build/' // prod build paths
}

// path variables and config
var path = {

    // src paths
    htmlSource: [env.Source + '**/*.kit', env.Source + '**/*.html', '!' + env.Source + '/{_partials,_partials/**,assets,assets/**}'],
    sassSource: env.Source + 'assets/scss/',
    jsSource: env.Source + 'assets/js/',
    fontSource: env.Source + 'assets/font/',
    imgSource: env.Source + 'assets/img/' ,
    bowerSource: env.Source + 'assets/bower_components/' ,

    // test-build paths
    htmlTest: env.Test,
    cssTest: env.Test + 'assets/css/',
    jsTest: env.Test + 'assets/js/',
    fontTest: env.Test + 'assets/img/',
    imgTest: env.Test + 'assets/font/',

    // prod-build paths
    htmlProd: env.Prod,
    cssProd: env.Prod + 'assets/css/',
    jsProd: env.Prod + 'assets/js/',
    fontProd: env.Prod + 'assets/img/',
    imgProd: env.Prod + 'assets/fonts/'
}

// var cssOptim = $.lazypipe()
//     .pipe(cssc)
//     .pipe(csso)
//     .pipe(more)
//     .pipe(shrink);



var AUTOPREFIXER_BROWSERS = [
    'ie >= 10',
    'ie_mob >= 10',
    'ff >= 30',
    'chrome >= 34',
    'safari >= 7',
    'opera >= 23',
    'ios >= 7',
    'android >= 4.4',
    'bb >= 10'
];

//Markup / Kit Imports
gulp.task('markup', function() {
    return gulp.src(path.htmlSource)
        .pipe($.kit())
        .pipe(gulp.dest(path.htmlTest))
        .pipe($.size({
            title: 'markup'
        }))
        .pipe($.browserSync.reload({
            stream: true
        }))
        .pipe($.notify({
            message: 'Markup task complete'
        }));

});


// Styles
gulp.task('styles', function() {
    return gulp.src(path.sassSource + 'app.scss') //gets main app SCSS
        //   .pipe($.scssLint()) Fix scsslint
          .pipe($.sourcemaps.init()) // Initializes sourcemap
        .pipe($.sass({
            outputStyle: "nested",
            errLogToConsole: true
        })) //outputs SCSS to CSS
         .pipe($.autoprefixer(AUTOPREFIXER_BROWSERS)) //parses through Autoprefixer
        
         .pipe($.bless()) //Checks for IE9 CSS selector limit
        .pipe($.rename({
            suffix: '.min'
        })) //appends .min suffix
        .pipe($.sourcemaps.write(".")) //adds sourcemaps
        .pipe(gulp.dest(path.cssTest)) // writes app.min.css to build/assets/css
        .pipe($.size({
            title: 'styles'
        }))
        .pipe($.filter(env.Test + 'assets/css/*.css')) //filtering stream to live-inject only CSS files
        .pipe($.browserSync.reload({
            stream: true
        })) // Live reload
        .pipe($.notify({
            message: 'Styles task complete'
        }));
});


gulp.task('flattenMarkup', function() {
    return gulp.src(path.htmlTest + '**/*.html')
        .pipe($.smoosher())
        .pipe($.htmlmin({
            collapseWhitespace: true,
            removeComments: true,
            minifyJS: true,
            minifyCSS: true,
            minifyURLs: true
        }))
        .pipe(gulp.dest(path.htmlProd))
});

// UnCSS --Currently, this does not pick up styles added through user interactions. Therefore, we must EITHER identify the classes to ignore (so they're added) or concat individual SCSS components afterwards
gulp.task('uncss', function() {
    return gulp.src(path.cssTest + 'app.min.css')
        .pipe($.uncss({
            html: [path.htmlTest + 'index.html', path.htmlTest + 'buildings/bourns/a125.html'],
            timeout: 6000,
            // ignore: [
            //         'selector',
            //         selector2/
            //       ]
            ignoreSheets: [/fast.fonts/],

        }))
         .pipe($.rename({
            suffix: '.uncss'
        })) 
        .pipe(gulp.dest(path.cssTest))
});


//  .pipe($.combinemq())

//Outputs CSS styles wrongfully stripped by UNCSS
 gulp.task('uncss-ignored-styles', function() {
    return gulp.src(path.sassSource + 'uncss-additional.scss') //get additional component css
        .pipe($.sass({
            style: 'expanded',
            errLogToConsole: true
        })) //outputs SCSS to CSS
        .pipe($.autoprefixer(AUTOPREFIXER_BROWSERS)) //parses through Autoprefixer
        .pipe(gulp.dest(path.cssTest)) // writes app.min.css to build/assets/css
        .pipe($.size({
            title: 'uncss-additional-styles'
        }))
        .pipe($.notify({
            message: 'uncss-additional-styles task complete'
        }));
});


gulp.task('flattenCSS', function() {
    gulp.src([path.cssTest + 'app.min.uncss.css', path.cssTest + 'uncss-additional.min.css'])
        .pipe($.concat('app.min.css'))
        .pipe(gulp.dest(path.cssProd))
});


// // Copy Web Fonts To Dist
// gulp.task('fonts', function() {
//     return gulp.src(['app/fonts/**'])
//         .pipe(gulp.dest('dist/fonts'))
//         .pipe($.size({
//             title: 'fonts'
//         }));
// });


// // Scripts
// gulp.task('scripts', function() {
//     return gulp.src([path.src + 'assets/js/app.js'], {
//             base: "src/"
//         }) // gets main app JS
//         .pipe($.include()) // looks for any other JS includes in app JS
//         .pipe($.jshint()) // parses through JS linter for bug reporting
//         .pipe($.jshint.reporter('default')) // default jshint settings
//         .pipe($.rename({
//             suffix: '.min'
//         })) // appends .min suffix
//         .pipe($.sourcemaps.init()) // Initializes sourcemap
//         .pipe($.uglify()) // minifies JS
//         .pipe($.sourcemaps.write(".")) //adds sourcemaps
//         .pipe(gulp.dest(path.test)) // writes app.min.js to build/assets/js
//         .pipe($.size({
//             title: 'scripts'
//         }))
//         .pipe($.notify({
//             message: 'Scripts task complete'
//         }));
// });

// // Images
// gulp.task('images', function() {
//     return gulp.src([path.src + 'assets/img/**/*', path.src + 'buildings/**/*.{svg,png,jpg}', path.test + 'virtual/**/*.{png,jpg,gif}', path.test + 'ai-cache/**/*.{png,jpg}'], {
//             base: "src/"
//         })
//         .pipe($.cache($.imagemin({
//             optimizationLevel: 4,
//             progressive: true,
//             interlaced: true,
//             svgoPlugins: [{removeViewBox: false}],
//             use: [pngquant()]
//         })))
//         .pipe(gulp.dest(path.test))
//         .pipe($.size({
//             title: 'images'
//         }))
//         .pipe($.browserSync.reload({
//             stream: true
//         })) // Live reload
//         .pipe($.notify({
//             message: 'Images task complete'
//         }));
// });

//Clean Sketch (strips colors?)
// gulp.task('icons', function() {
//   return gulp.src(path.test + 'assets/img/*.svg')
//     .pipe($.cleansketch())
//     .pipe(gulp.dest(path.test + 'assets/img/'));
// });



// Generate & Inline Critical-path CSS. 
//Make sure the CSS path in the HTML does not start with '/' if using extract:true!
//Any NON-CSS complaint stuff like @-moz-document url-prefix() can break the parser's output. If needed, use inline styles
// gulp.task('critical', function() {
//     return gulp.src(path.test + '**/*.html')
//         .pipe(critical({
//             base: path.test,
//             width: 1024,
//             height: 768,
//             minify: false, //leave false, bug (and it's minified with previous task)
//             extract: false
//         }))
//         .pipe($.rename({
//             suffix: '.critical'
//         }))
//         .pipe(gulp.dest(path.test));
// });


// // Generate & Inline Critical-path CSS
// gulp.task('critical', ['copystyles'], function (cb) {

//     // At this point, we have our
//     // production styles in main/styles.css

//     // As we're going to overwrite this with
//     // our critical-path CSS let's create a copy
//     // of our site-wide styles so we can async
//     // load them in later. We do this with
//     // 'copystyles' above

//     critical.generate({
//         base: path.test,
//         src: 'index.html',
//         dest: 'assets/css/site.css',
//         width: 1024,
//         height: 768,
//         minify: true
//     }, function(err, output){
//         critical.inline({
//             base: path.test,
//             src: 'index.html',
//             dest: 'index-critical.html',
//             minify: true
//         });        
//     });
// });



//Browser-Sync
gulp.task("browser-sync", function() {
    $.browserSync({
        server: {
            baseDir: "./test-build/"
        }
    });
});


// //Watch
// gulp.task('watch', function() {
//     gulp.watch(path.src + '**/*.kit', ['markup']);
//     gulp.watch(path.src + '**/*.{svg,png,jpg,gif}', ['images']);
//     //   gulp.watch(path.test + '**/*.svg', ['icons']);
//     gulp.watch(path.src + '**/*.scss', ['styles']);
//     gulp.watch("src/**/*.js", ['scripts', $.browserSync.reload]);

// });

gulp.task('default', ['markup', 'images']);

// Default task
//gulp.task('default', ['markup', 'images', /*'icons',*/ 'styles', 'scripts', 'browser-sync', 'watch']);
//gulp.task flatten

**Comment by alanontheweb** [comment]
I sorted it out. There was a comment at the very bottom that was breaking it. Kind of weird, but it works now! Thanks again =)

**Comment by NicoSantangelo** [comment]
Wow that's weird. Sorry I didn't help more, thanks for letting me know!

If it happens again I can put some explanation on the README :)
