### ISSUE TITLE
[feature request]: remove .sublime-gulp.cache with a quick command

### ISSUE THREAD

**Issue by OctoD** [NicoSantangelo/sublime-gulp#20]
Hello! Really loving your plugin! 

I suggest it would be a nice idea to implement a quick command to remove the tasks cache using a quick command. It would be useful for speeding up task writing and testing.

P.S.
Forgive me for my poor english.

**Comment by NicoSantangelo** [comment]
Hello! thanks :)

You mean having a command like `Gulp: Clear cache` which deletes the `.sublime-gulp.cache` file, right?

If so, I think it's a good idea (:

**Comment by OctoD** [comment]
Yep! Forgive me if I explained the idea badly :)

**Comment by NicoSantangelo** [comment]
Ok!

I'll give it a try when I have some time (I think this Sunday).

Thanks a lot for the suggestion

**Comment by OctoD** [comment]
Great! Thank you!

**Comment by NicoSantangelo** [comment]
This should be up.

Let me know if it works as expected, thanks again for the suggestion.
