### ISSUE TITLE
Using with .nvmrc

### ISSUE THREAD

**Issue by gilesbutler** [NicoSantangelo/sublime-gulp#22]
Hey,

Since I started using NVM to manage my versions of Node, SublimeGulp has stopped working.

I get the following error ````Error: `libsass` bindings not found. Try reinstalling `node-sass`?````
The system version of Node doesn't work with my projects packages and sublime is trying to use that version maybe?

Is there anyway around this?

Thanks

**Comment by NicoSantangelo** [comment]
Never used NVM myself but have you tried overriding your `PATH` inside SublimeGulp ? (using [exec_args](https://github.com/NicoSantangelo/sublime-gulp#exec_args) )

**Comment by gilesbutler** [comment]
Thanks Nico, that worked :+1: 

I used ````nvm which 0.12```` - ````0.12```` is the version number in my [.nvmrc](https://github.com/creationix/nvm) file. That gave me the path to that exact version of node and then I put that as my exec_args setting.

**Comment by NicoSantangelo** [comment]
Glad I could help!

Thanks for letting me know.
