### ISSUE TITLE
Gulp 4 compatibility

### ISSUE THREAD

**Issue by Smuliii** [NicoSantangelo/sublime-gulp#23]
Even though gulp 4 isn't out yet, I've been using the alpha version for a little while now. And I noticed that this plugin seems to have some problems with the new task system.

It gives no errors but `tasks` object in `.sublime-gulp.cache` file is empty.

You can easily test this with any project by first installing new CLI tools globally:
`$ npm install gulpjs/gulp-cli#4.0 -g`

And then updating gulp locally:
`$ npm install gulpjs/gulp.git#4.0`

**Comment by NicoSantangelo** [comment]
Wow, thanks a lot for the heads up. I'm traveling in a couple of days but when I get back I'll definitely take a look.

Do you know when is `gulp` 4 scheduled to release?

**Comment by Smuliii** [comment]
I don't think there's any set date (anymore). So I guess it will be released as soon as possible.

**Comment by NicoSantangelo** [comment]
@Smuliii  Well this should be fixed.

Please let me know if is working for you (it may take a bit to update if you're using Package Control) and thanks again.

**Comment by Smuliii** [comment]
Yep, seems to be working. Thanks!
