### ISSUE TITLE
Results do not autoclose 

### ISSUE THREAD

**Issue by rubjo** [NicoSantangelo/sublime-gulp#28]
Thank you for making this plugin!

The `results_autoclose_timeout_in_milliseconds` option has no effect for me on ST3/OSX, the panel (or tab) stays open. Other options work fine.

**Comment by NicoSantangelo** [comment]
Hum, testing in Yosemite 10.10.3 works fine for me, are you using any other setting with `results_autoclose_timeout_in_milliseconds` ?

Also, can you please tell me if you can see any errors on the Sublime Text console (``Ctrl + ` ``) when running the tasks?

Thanks!

**Comment by rubjo** [comment]
Latest versions here. No other settings than `autoclose` on 1000. No errors or other messages in the console other than `reloading Packages/User/Gulp.sublime-settings` when I try to change the settings.

No biggie, I'll just close the panel and bring it back up manually when I need to. I am using quite a few other packages, maybe they are interfering with sublime-gulp in some way.

**Comment by NicoSantangelo** [comment]
If you want, paste here your `Package Control.sublime-settings` file. I don't mind taking a look to see if there's any fixable conflict.

**Comment by rubjo** [comment]
Sure, here are my installed packages:

```
{
	"in_process_packages":
	[
	],
	"installed_packages":
	[
		"Alignment",
		"ASCII Decorator",
		"Autoprefixer",
		"Color Highlighter",
		"ColorPicker",
		"ColorSchemeSelector",
		"CSScomb",
		"Emmet",
		"Fix Mac Path",
		"Gulp",
		"HTML-CSS-JS Prettify",
		"HTML5",
		"jQuery",
		"Markdown Preview",
		"MarkdownEditing",
		"Package Control",
		"ReadmePlease",
		"Sass",
		"SassBeautify",
		"SFTP",
		"SideBarEnhancements",
		"StringEncode",
		"SublimeCodeIntel",
		"SublimeLinter",
		"SublimeLinter-contrib-jslint",
		"SublimeLinter-contrib-scss-lint",
		"SublimeLinter-csslint",
		"SublimeLinter-html-tidy",
		"SublimeLinter-phplint",
		"Text Pastry",
		"Theme - Spacegray",
		"Themr",
		"TrailingSpaces",
		"WordCount"
	]
}
```

**Comment by rubjo** [comment]
I'm sorry, turns out the `results_autoclose_timeout_in_milliseconds` option is honored and works after all, the panel autocloses when the gulp tasks finishes.

I assumed the timer was reset whenever new output was printed, so I thought the panel would close while a gulp watch task was running (as long as no new output was printed in the timeout period).

**Comment by NicoSantangelo** [comment]
Wow, thanks for the heads up!
It's not all bad, while trying your installed packages I really liked Text Pastry :D.

Thanks again and if anything comes up, let me know.
