### ISSUE TITLE
Run as root user / admin

### ISSUE THREAD

**Issue by jimbatamang** [NicoSantangelo/sublime-gulp#30]
How can I run gulp task as a root user while using sublime-gulp plugin?

**Comment by NicoSantangelo** [comment]
Hum, as of right now, you can't. 

To my knowledge, `gulp` isn't really intended to be used as `root`, do you really need to run it like that?

**Comment by jimbatamang** [comment]
May be if it's my OS/Machine issue or not but when I run gulp tasks (which includes imagemin, sourcemap) without super user, it can't replace the old files.

**Comment by NicoSantangelo** [comment]
I tried a bit and couldn't run a `sudo` command from Sublime. I'll keep trying and let you know either way

**Comment by NicoSantangelo** [comment]
I tried running the task as an admin from inside Sublime and it just couldn't be done. For now, it seems like a _limitation_ of the editor.
If I can find a workaround for this I'll reopen the issue, sorry.
