### ISSUE TITLE
Gulpfile errors if the last line is a comment

### ISSUE THREAD

**Issue by Minopolis** [NicoSantangelo/sublime-gulp#42]
So I was getting an error in my gulpfile and had absolutely no idea what it was caused by and it turns out that it the last line of my gulpfile is an inline comment, it errors.

Example code:

	// Include gulp
	var gulp = require('gulp');

	// Changed html / php
	gulp.task('test', function(files) {
		console.log("I work!");
	});

	// Default Task
	gulp.task('default', ['test']);

	//You shall not work

The code works if executed by the command line and multiline comments work fine.
I am using OSX 10.11 and the latest gulp version

**Comment by NicoSantangelo** [comment]
Yes!
This is a known bug, #37 , I didn't have time (yet) to fix it but it's on the roadmap!

If you don't mind, I'll close this so it doesn't get duplicated but for any more feedback please let me know in the other issue.

Thanks :)

**Comment by Minopolis** [comment]
Oh, my bad, sorry about that.
