### ISSUE TITLE
Output view issue for morgan plugin

### ISSUE THREAD

**Issue by lunivm** [NicoSantangelo/sublime-gulp#47]
I'm using morgan plugin (https://www.npmjs.com/package/morgan) in my MEAN app. Unfortunately this plugin's output has broken view in console. Attaching screenshot of output result.

![st-gulp-issue](https://cloud.githubusercontent.com/assets/3826134/9527392/8cbb7062-4cf7-11e5-88b0-0f0d6bce5bc7.png)

**Comment by NicoSantangelo** [comment]
It seems to be a problem with the coloring output of the terminal, I'll check it out.

Are you using Windows and Sublime Text 3?

**Comment by lunivm** [comment]
I'm using Windows 7 and Ubuntu 14.04 (on both OS issue reproduces in the same way), Sublime Text 3. 

Coloring output of Gulp and Gulp plugins(gulp-nodemon in my case) are ok. It seems like this issue is reproducible with output that comes from Morgan package output. Attaching one more screenshot.

![st-gulp-issue2](https://cloud.githubusercontent.com/assets/3826134/9529131/4ea6abc0-4d01-11e5-83eb-8c3356f21562.png)


Thank you!

**Comment by NicoSantangelo** [comment]
I meant the ANSI escape codes for coloring! Take a look at [Sublime ANSI](https://github.com/aziz/SublimeANSI)

I'll see if I can remove/highlight them when I have a bit of free time :)

**Comment by NicoSantangelo** [comment]
This is up (version `5.0.1`)

Sorry it took so long, let me know if it works up for you!

**Comment by lunivm** [comment]
Hello, sorry for a late response. Yes, it works, no more escape codes in output. Thank you!
