### ISSUE TITLE
Project specific settings not working

### ISSUE THREAD

**Issue by simonknittel** [NicoSantangelo/sublime-gulp#53]
I'm currently having a problem, that my project specific settings are not working.

My .sublime-project file looks like this
```json
{
    "folders":
    [
        {
            "path": "."
        }
    ],
    "Gulp": {
        "results_in_new_tab": true,
        "gulpfile_paths": [
            "sub-directory/sub-directory-2"
        ]
    }
}
```
Neither the "results_in_new_tab" nor the "gulpfile_paths" have any effect. Changing the "folders" setting does have effects, so the .sublime-project file itself gets read.

I'm using Sublime Text Build 3083.

Any ideas?

**Comment by NicoSantangelo** [comment]
Hm you seem to be using it correctly.
Could you tell me what gets printed on the `Sublime Text` console (`View -> Show console`) when you execute:

```
sublime.active_window().project_data()
```

Also, does this feature work in any other Sublime project?
Which OS are you using?

**Comment by simonknittel** [comment]
The console command outputs this
```
{'folders': [{'path': '.'}], 'Gulp': {'results_in_new_tab': True, 'gulpfile_paths': ['application/drag-n-drop-test']}}
```

I'm using Windows 10 and it does not work in any other project.

**Comment by NicoSantangelo** [comment]
That's weird, I was expecting to see `{ 'folders': [{'path': '.'}] }`.

I have just tried in Windows 8 and it seems to be working so it _might_ be a Windows 10 issue.
If you don't mind, try the following:

1. Make sure you open your project with `Open Project` (just in case)
2. Write the following in the console
    * `from Gulp.settings import Settings`
    * `from Gulp.settings import ProjectData`
    * `Settings().get('results_in_new_tab')`
    * `ProjectData().get("results_in_new_tab", "Not here")`

It should look something like this:

![sbt](https://cloud.githubusercontent.com/assets/692077/10882477/d40bf87a-8149-11e5-9fa2-2cf6db44bc51.gif)

**Comment by simonknittel** [comment]
Hm, seems like my sublime-gulp installation broke. The first two commands said, that a Module named "Gulp.settings" could not be found so I decided to remove and reinstall the package with the package manager and now it works. The interesting part is, that I know the package itself worked before, because I tested that.

**Comment by NicoSantangelo** [comment]
Hm I hope it was an isolated issue because that could be very frustrating.

Thanks a lot for giving me a hand diagnosing this!, I'll close the issue but let me know if you have another problem.

**Comment by simonknittel** [comment]
Thank you for your help!
