### ISSUE TITLE
Remove CR from output

### ISSUE THREAD

**Issue by roccivic** [NicoSantangelo/sublime-gulp#55]
On Windows the CR character (0x0D) seems to be incorrectly rendered in the console output window.

![capture](https://cloud.githubusercontent.com/assets/1194964/11962414/97ea35b8-a8d7-11e5-93c6-8d9eb22b9d81.PNG)

**Comment by NicoSantangelo** [comment]
Woops, I had some trouble with CR characters a while ago ([hence this line](https://github.com/NicoSantangelo/sublime-gulp/blob/master/cross_platform_codecs.py#L10)).
If you don't mind, can you tell me which plugin is printing that to the console so I can be more confident with the fix?

Thanks!

**Comment by roccivic** [comment]
gulp-mocha, I think

Have a look around if you like: https://github.com/roccivic/cron-converter

**Comment by NicoSantangelo** [comment]
Awesome, it might take me a few days with the holidays but I'll use your project as reference

**Comment by NicoSantangelo** [comment]
Hey there, I finally had some time to test this out today but running `gulp` on Windows 8.1 gives me this output:

![gulp](https://cloud.githubusercontent.com/assets/692077/12081294/8cb5d672-b253-11e5-86fb-2bab49afb0e3.PNG)


I think I'm missing something

**Comment by roccivic** [comment]
I switched from mocha to tape since. Sorry I didn't say anything.
Try checking out rev 7aaa4933

**Comment by NicoSantangelo** [comment]
Oooh ok! thanks for letting the heads up

**Comment by NicoSantangelo** [comment]
This is fixed (should take a moment to update), thanks a lot for the issue and followup
