### ISSUE TITLE
Sublime key bindings doesnt work

### ISSUE THREAD

**Issue by tiagoporto** [NicoSantangelo/sublime-gulp#57]
The default key binding `ctrl+/` (toggle commet) doesnt work with the syntax

**Comment by NicoSantangelo** [comment]
You mean in a `Gulp Results` tab? If that's the case you're right but what would be the desired result?

**Comment by tiagoporto** [comment]
My `gulpfile.js` uses the syntax `Gulpfile JS`, when I want comment some part of the code I use `ctrl+/`. But nothing happens.

The `gulpfile.js` is a javascript file and the key bindings (toggle comments) should comment lines likes

```js
// var myVar = 'test';
```

If I change the syntax of  `gulpfile.js` to JavaScript, works again.

**Comment by NicoSantangelo** [comment]
Hm the thing is that this package does not define the `Gulpfile JS` syntax, it contains the `Gulp Results` syntax used on the panel/tab when running `gulp`.

The culprit could be another package or am I missing something?

**Comment by NicoSantangelo** [comment]
I'm closing this for the sake of completeness, but if you have any feedback I'll be happy to re-open it!
