### ISSUE TITLE
Perform gulp_kill before performing tasks_on_save,

### ISSUE THREAD

**Issue by guohuihot** [NicoSantangelo/sublime-gulp#63]
Perform gulp_kill before performing tasks_on_save, or a task will be executed two times, meaning that I think the task is to re execute.

**Comment by NicoSantangelo** [comment]
Good catch, I think I'll add a separate flag for this because maybe it's not desired to _always_ kill before running.

**Comment by NicoSantangelo** [comment]
This is up in version `v5.4.0`.

You can now set [`kill_before_save_tasks`](https://github.com/NicoSantangelo/sublime-gulp#kill_before_save_tasks) on your settings

Let me know how it goes!
