### ISSUE TITLE
List Task to run

### ISSUE THREAD

**Issue by danilomelo** [NicoSantangelo/sublime-gulp#64]
List task registred on gulp file to avoid repeat the workflow:
Open command pallete -> run taks -> write text to run -> enter

On listing tasks:
List task -> choose -> enter

**Comment by NicoSantangelo** [comment]
Can you clarify this one a bit ?

I think I'm misunderstanding the request but it looks like it could be solved by using a [Keyboard Shortcut](https://github.com/NicoSantangelo/sublime-gulp#shortcut-keys)

**Comment by danilomelo** [comment]
List Tasks is simple.

Catch all gulp.task registred on gulp file e show after type on command
pallete: "Gulp: List Tasks"

2016-05-27 10:44 GMT-03:00 Nicolás Santángelo <notifications@github.com>:

> Can you clarify this one a bit ?
>
> I think I'm misunderstanding the request but it looks like it could be
> solved by using a Keyboard Shortcut
> <https://github.com/NicoSantangelo/sublime-gulp#shortcut-keys>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/NicoSantangelo/sublime-gulp/issues/64#issuecomment-222150064>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AB1ewwsccrZFV5861Dj-ByLPFToAQMiAks5qFvVUgaJpZM4In6bb>
> .
>



-- 
[]'s
Danilo.

**Comment by NicoSantangelo** [comment]
But isn't that the way the `Gulp` command works today ?

![list](https://cloud.githubusercontent.com/assets/692077/15620755/9e8c0d66-2432-11e6-96a4-99352ea88664.gif)

**Comment by danilomelo** [comment]
Ow man, sorry, I don't see it  :)

2016-05-27 17:44 GMT-03:00 Nicolás Santángelo <notifications@github.com>:

> But isn't that the way the Gulp command works today ?
>
> [image: list]
> <https://cloud.githubusercontent.com/assets/692077/15620755/9e8c0d66-2432-11e6-96a4-99352ea88664.gif>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/NicoSantangelo/sublime-gulp/issues/64#issuecomment-222248942>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AB1ew1uw7E-btCbN95bDTWtF2MFwRL2yks5qF1e5gaJpZM4In6bb>
> .
>



-- 
[]'s
Danilo.

**Comment by NicoSantangelo** [comment]
No problem :)
