### ISSUE TITLE
Never shows task chooser, but shows working in footer bar

### ISSUE THREAD

**Issue by custa1200** [NicoSantangelo/sublime-gulp#66]
Hi,
I have installed sublime-gulp into the latest version of Sublime 3 (3114) but it what I select it from the Sublime menu I do not get shown the task chooser yet the Gulp: Working is shown in the footer with the progress indicator moving. Not sure what is wrong. Running the latest version of OSX on a new MacBook

**Comment by NicoSantangelo** [comment]
Hm that's weird, did you take a look at [Troubleshooting section](https://github.com/NicoSantangelo/sublime-gulp#troubleshooting)?

If that does not help, can you tell me the output of the Sublime Console after you run the command ? (you can access it from `View -> Show Console`)

**Comment by custa1200** [comment]
After I command shift p and select Gulp nothing shows in the console. the following is what loads when I launch Sublime.

startup, version: 3114 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/mjohnston/Library/Application Support/Sublime Text 3/Packages
state path: /Users/mjohnston/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/mjohnston/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.189636
using gpu buffer for window
startup time: 0.266539
unsupported pixel depth
first paint time: 0.309483
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin ColorSchemeSelector.ColorSchemeSelector
reloading plugin CSS3.css3_completions
reloading plugin CSS3.rgb_to_hex
reloading plugin CSS3.validator
reloading plugin EditorConfig.EditorConfig
reloading plugin Fix Mac Path.FixPath
reloading plugin HTML5.encode_html_entities
reloading plugin HTML5.html_completions
reloading plugin npm.cli
reloading plugin npm.command
reloading plugin npm.install
reloading plugin npm.link
reloading plugin npm.list
reloading plugin npm.outdated
reloading plugin npm.rm
reloading plugin npm.run_arbitrary
reloading plugin npm.script
reloading plugin npm.search
reloading plugin npm.settings
reloading plugin npm.test
reloading plugin npm.update
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin Path Translator.PathTranslator
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin Stylus.Stylus
reloading plugin Themr.themr
reloading plugin Grunt.main
reloading plugin Gulp.base_command
reloading plugin Gulp.cross_platform_codecs
reloading plugin Gulp.dir_context
reloading plugin Gulp.event_task
reloading plugin Gulp.gulp
reloading plugin Gulp.gulp_version
reloading plugin Gulp.hasher
reloading plugin Gulp.plugins
reloading plugin Gulp.progress_notifier
reloading plugin Gulp.settings
plugins loaded
Unable to fetch update url contents
Package Control: Skipping automatic upgrade, last run at 2016-06-01 00:23:25, next run at 2016-06-01 01:23:25 or after

**Comment by custa1200** [comment]
I can run all commands from the Tools > Gulp menu except for List Tasks to run

**Comment by custa1200** [comment]
It does create and remove a tmp file before it deletes it and creates sublime-gulp.cache file but never shows the task list :(

**Comment by NicoSantangelo** [comment]
Weird!

*. First of all, could you paste here the contents of the `. sublime-gulp.cache` file ?
*. Next, do you see a `sublime-gulp.log` file ?
*. Lastly, could you try in a stripped down example ?, by that I mean a `gulpfile.js` like this:

```
var gulp = require('gulp');

gulp.task('simple', function() {
  console.log('Hey!')
});
```

to see what happens

**Comment by custa1200** [comment]
cache file contents: 

{"/Users/mjohnston/projects/styleglide/gulpfile.js":{"sha1":"c68a41a181776df813089b40763ca87f155b28e0","tasks":{"svgsprite":{"name":"svgsprite","dependencies":"images"},"images":{"name":"images","dependencies":""},"sourcecss":{"name":"sourcecss","dependencies":""},"specs":{"name":"specs","dependencies":""},"css":{"name":"css","dependencies":"specs"},"default":{"name":"default","dependencies":"specs css"}}}}

There is no log file created. :(

**Comment by custa1200** [comment]
When I try to run with the basic gulfile.js I get:
<img width="532" alt="screen shot 2016-06-01 at 11 04 54 am" src="https://cloud.githubusercontent.com/assets/161224/15695292/f7e80a68-27e8-11e6-8953-d10d88a6accc.png">

Wen I run arbitrary task and put simple it it runs.

**Comment by custa1200** [comment]
So Just noticed in that dialog It is looking for "Projects", I had since named my folder to "projects", arghhh. Any idea how I can safely change this to "projects" and not have Sublime Gulp break?

**Comment by custa1200** [comment]
Seems after rejigging I now have it working with "projects" it's a bit of a gotcha though if somebody renames a folder. not sure if others have run into it or it need a note describe the issue.

**Comment by NicoSantangelo** [comment]
First of all, thanks **a lot** for the followup, I can't believe this issue didn't come up sooner!.

I'm going to do the following:

1. Write a warning on the README pointing to this issue (so if you don't mind leave it open so it acts as a reminder)
2. See if the package can perform a little check to verify the path stored on the cache and at least throw a warning

Again thanks a lot for your help and I'm glad you got it working

**Comment by custa1200** [comment]
Thank you, it was that last step of where I saw the case difference on the path in the dialog which triggered the thought.

**Comment by NicoSantangelo** [comment]
The notice is up! thanks again for the help
