### ISSUE TITLE
Colors with gulp-util.colors

### ISSUE THREAD

**Issue by TCB13** [NicoSantangelo/sublime-gulp#75]
Hello,

I was trying this package and it works just fine, however I was trying to add some colors to the output of my gulp tasks and it doesn't print them.

I'm using the `gulp-util` module to color my output, and it works perfectly on the terminal but not under the sublime result window. Why? Can it be fixed?

Thank you.

**Comment by NicoSantangelo** [comment]
Hello!

The output you see on Sublime Text it's just the text `gulp` writes to `STDOUT` being added to a regular tab. Sadly there's no way to actually see the output formatted as like you do in the Terminal.

The color you see while using the package is defined [here](https://github.com/NicoSantangelo/sublime-gulp/tree/master/syntax), the solution would be creating your own [Syntax Definition](https://www.sublimetext.com/docs/3/syntax.html) and then using it by overriding the [syntax](https://github.com/NicoSantangelo/sublime-gulp#syntax) option of this package.

It's annoying, I know :(

**Comment by TCB13** [comment]
@NicoSantangelo thanks for confirming my fears, I had run with this "issue" with build systems in the past. Frankly if the way to create a Syntax Definition it's not worth it. You can close this!
