### ISSUE TITLE
import error about Settings

### ISSUE THREAD

**Issue by SejoongDeJang** [NicoSantangelo/sublime-gulp#76]
Hi. I'm sejoong. This is my first issue, I might have some mistake.
Since previous week, I didn't use gulp at sublime command pallete.

When I saw log at starting sublime, there are some error like followed:

Reloading plugin C:\Users\xxx\AppData\Roaming\Sublime Text 2\Packages\Gulp\base_command.py
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 62, in reload_plugin
    m = imp.load_module(modulename, *m_info)
  File ".\base_command.py", line 12, in <module>
    from settings import Settings
ImportError: cannot import name Settings
Reloading plugin C:\Users\xxx\AppData\Roaming\Sublime Text 2\Packages\Gulp\caches.py
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 62, in reload_plugin
    m = imp.load_module(modulename, *m_info)
  File ".\caches.py", line 11, in <module>
    from settings import Settings
ImportError: cannot import name Settings
Reloading plugin C:\Users\xxx\AppData\Roaming\Sublime Text 2\Packages\Gulp\cross_platform_codecs.py
Reloading plugin C:\Users\xxx\AppData\Roaming\Sublime Text 2\Packages\Gulp\cross_platform_process.py
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 62, in reload_plugin
    m = imp.load_module(modulename, *m_info)
  File ".\cross_platform_process.py", line 17, in <module>
    from settings import Settings
ImportError: cannot import name Settings
Reloading plugin C:\Users\xxx\AppData\Roaming\Sublime Text 2\Packages\Gulp\dir_context.py
Reloading plugin C:\Users\xxx\AppData\Roaming\Sublime Text 2\Packages\Gulp\event_task.py
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 62, in reload_plugin
    m = imp.load_module(modulename, *m_info)
  File ".\event_task.py", line 11, in <module>
    from settings import Settings
ImportError: cannot import name Settings
Reloading plugin C:\Users\xxx\AppData\Roaming\Sublime Text 2\Packages\Gulp\gulp.py
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 62, in reload_plugin
    m = imp.load_module(modulename, *m_info)
  File ".\gulp.py", line 24, in <module>
    from base_command import BaseCommand
  File ".\base_command.py", line 12, in <module>
    from settings import Settings
ImportError: cannot import name Settings

My enviroment is Window7 64bit.

P.S
Appreciate your packages. It's make me comfortable.

**Comment by NicoSantangelo** [comment]
Hello, Thanks for the report!

I'll try it out on windows to see if I can reproduce it (it's working fine on El Capitan) but, if you don't mind, reinstalling the package fixes it?

**Comment by SejoongDeJang** [comment]
@NicoSantangelo When I tried to reinstall, it was always occured same error.

**Comment by SejoongDeJang** [comment]
Now I get list! Maybe install unspported window package lead error. Thanks @NicoSantangelo !

**Comment by NicoSantangelo** [comment]
Woohooo 🎉 .

I read this on my email and forgot to answer
