### ISSUE TITLE
I had an infinite loop when run gulp from sublime. But in bash everything is ok

### ISSUE THREAD

**Issue by AmeliePoulain92** [NicoSantangelo/sublime-gulp#80]

**Comment by NicoSantangelo** [comment]
Hello!

Can you give me a bit more info? like which command were you using and on which OS?
Also how do you know it's an infinite loop?

Thanks!

**Comment by AmeliePoulain92** [comment]
Hello, NicoSantangelo! 

I'm using Win10 i use default task run in sublime gulp. First of all, the console not showing information about progress in development. Just shows this http://prntscr.com/e5y2l1 permanently. and when i work on my project, gulp reloads page just a few times and then reloads it every second without saving, and i can't reload the page. There weren't these problems later. I've enjoy this plugin, you do good work. So, maybe you just can help me with this? Thanks!

**Comment by NicoSantangelo** [comment]
Ok! I'll dust out my Windows box to try, but I need you to give me a rough idea of which tasks you use on your gulpfile to check what the problem might be

**Comment by AmeliePoulain92** [comment]
Hi, NicoSantangelo! I don't know what happened but issue has gone. It works fine for now. thanks for your replies.

**Comment by NicoSantangelo** [comment]
Wow that's good news 🎉 , I'll close this but don't hesitate to ping me again if you have a problem

**Comment by AmeliePoulain92** [comment]
thanks for your help!
